[package]
name = "todos"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dialoguer = { version = "0.10.3", features = ["fuzzy-select"] }
jwalk = "0.8.1"
nom = "7.1.3"
